# Generated by Django 6.0.1 on 2026-02-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('fee_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'fee_schedules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayerNetwork',
            fields=[
                ('network_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('network_name', models.CharField(blank=True, max_length=100, null=True)),
                ('line_of_business', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'payer_networks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProviderOrganization',
            fields=[
                ('organization_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('npi', models.CharField(blank=True, max_length=15, null=True)),
                ('address_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provider_organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefGeoIndex',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('locality_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('gpci_work', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('gpci_pe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('gpci_mp', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'ref_geo_indices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefModifier',
            fields=[
                ('modifier_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage_adjustment', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
            options={
                'db_table': 'ref_modifiers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeeScheduleRate',
            fields=[
                ('rate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_id', models.CharField(max_length=20)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_schedule', models.ForeignKey(db_column='fee_schedule_id', on_delete=django.db.models.deletion.CASCADE, to='core.feeschedule')),
            ],
            options={
                'db_table': 'fee_schedule_rates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rule_type', models.CharField(max_length=10)),
                ('methodology_code', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('specificity_score', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('effective_start_date', models.DateField(default='1900-01-01')),
                ('base_fee_schedule', models.ForeignKey(db_column='base_fee_schedule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feeschedule')),
            ],
            options={
                'db_table': 'pricing_rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PricingRuleCondition',
            fields=[
                ('condition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=50)),
                ('operator', models.CharField(default='EQ', max_length=10)),
                ('attribute_value', models.CharField(max_length=255)),
                ('pricing_rule', models.ForeignKey(db_column='rule_id', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.pricingrule')),
            ],
            options={
                'db_table': 'pricing_rule_conditions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProviderContract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('legacy_contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('network', models.ForeignKey(db_column='network_id', on_delete=django.db.models.deletion.CASCADE, to='core.payernetwork')),
                ('provider_org', models.ForeignKey(db_column='provider_org_id', on_delete=django.db.models.deletion.CASCADE, to='core.providerorganization')),
            ],
            options={
                'db_table': 'contracts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='contract',
            field=models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, to='core.providercontract'),
        ),
        migrations.AddField(
            model_name='payernetwork',
            name='payer_org',
            field=models.ForeignKey(db_column='payer_org_id', on_delete=django.db.models.deletion.CASCADE, to='core.providerorganization'),
        ),
        migrations.CreateModel(
            name='RefProcedureCode',
            fields=[
                ('code_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_type', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('work_rvu', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('pe_rvu', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('mp_rvu', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('effective_start_date', models.DateField(default='1900-01-01')),
                ('effective_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_procedure_codes',
                'managed': True,
                'unique_together': {('code_id', 'code_type')},
            },
        ),
    ]
