# Generated by Django 6.0.1 on 2026-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('BASE', 'Base Rate (Standard)'), ('ADD_ON', 'Add-on (Cumulative)'), ('CAP', 'Cap / Limit (Restrictive)'), ('STOP_LOSS', 'Stop Loss (Override)')], default='BASE', help_text='BASE = Exclusive (only one runs). ADD_ON = Adds to total.', max_length=20),
        ),
    ]
