# Generated by Django 6.0.1 on 2026-02-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingrule_rule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrule',
            name='rule_priority',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='specificity_score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('BASE', 'Base Rate (Standard)'), ('ADD_ON', 'Add-on (Cumulative)'), ('CAP', 'Cap / Limit (Restrictive)'), ('STOP_LOSS', 'Stop Loss (Override)')], default='BASE', help_text='BASE = Exclusive (highest score wins). ADD_ON = Cumulative.', max_length=20),
        ),
    ]
