# Generated by Django 6.0.1 on 2026-02-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pricingrule_rule_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='threshold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trigger for Stop Loss', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('BASE', 'Base Rate (Standard)'), ('ADD_ON', 'Add-on (Cumulative)'), ('ADJUSTMENT', 'Adjustment (Multiplier)'), ('CAP', 'Cap / Limit (Restrictive)'), ('STOP_LOSS', 'Stop Loss (Outlier)')], default='BASE', help_text='BASE=Exclusive. ADD_ON=Sum. ADJUSTMENT=Multiply. STOP_LOSS=Outlier.', max_length=20),
        ),
    ]
