# Generated by Django 5.2.11 on 2026-02-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rulehistory_id'),
        ('core', '0004_pricingrule_effective_end_date'),
    ]

    operations = [
    ]
