# Generated by Django 5.2.11 on 2026-02-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phase6_contract_outlier_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractoutlierrule',
            options={'managed': True, 'ordering': ['contract', '-priority', 'effective_start_date']},
        ),
        migrations.AlterField(
            model_name='rulehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
