# Generated by Django 5.2.11 on 2026-02-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_step12c_conditions_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractbaserate',
            options={'managed': True, 'ordering': ['version', 'rate_type']},
        ),
        migrations.AlterModelOptions(
            name='contractblendingrule',
            options={'managed': True, 'ordering': ['-priority', 'effective_start_date']},
        ),
        migrations.AlterModelOptions(
            name='contractcapfloor',
            options={'managed': True, 'ordering': ['-priority', 'effective_start_date']},
        ),
        migrations.AlterModelOptions(
            name='contractcarveout',
            options={'managed': True, 'ordering': ['version', 'code_type', 'code_value']},
        ),
        migrations.AlterModelOptions(
            name='contractproviderparticipation',
            options={'managed': True, 'ordering': ['contract', '-effective_start_date']},
        ),
        migrations.AlterModelOptions(
            name='contractscope',
            options={'managed': True, 'ordering': ['contract', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='contractstoplossrule',
            options={'managed': True, 'ordering': ['contract', '-priority', 'effective_start_date']},
        ),
        migrations.AlterModelOptions(
            name='contractversion',
            options={'managed': True, 'ordering': ['contract', '-version_number']},
        ),
        migrations.AlterModelOptions(
            name='validationresult',
            options={'managed': True, 'ordering': ['-validated_at', 'severity', 'conflict_type']},
        ),
        migrations.RemoveIndex(
            model_name='contractcapfloor',
            name='capfloor_version_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractcarveout',
            name='carveout_version_code_idx',
        ),
        migrations.AddField(
            model_name='contractversion',
            name='pricing_engine_mode',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('STAGED', 'Staged')], db_column='pricing_engine_mode', default='LEGACY', max_length=10),
        ),
        migrations.AlterField(
            model_name='contractblendingrule',
            name='blend_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contractblendingrule',
            name='conditions',
            field=models.JSONField(blank=True, help_text='Optional. Null = always apply. Schema: {"operator": "AND"|"OR", "conditions": [{"field": "procedure_code"|"billed_amount"|"units"|"claim_type"|"modifiers_count", "op": "eq"|"neq"|"gt"|"gte"|"lt"|"lte"|"in"|"not_in", "value": <scalar or list>}]}. No nested groups.', null=True),
        ),
        migrations.AlterField(
            model_name='contractcapfloor',
            name='conditions',
            field=models.JSONField(blank=True, help_text='Optional. Null = always apply. Schema: {"operator": "AND"|"OR", "conditions": [{"field": "procedure_code"|"billed_amount"|"units"|"claim_type"|"modifiers_count", "op": "eq"|"neq"|"gt"|"gte"|"lt"|"lte"|"in"|"not_in", "value": <scalar or list>}]}. No nested groups.', null=True),
        ),
        migrations.AlterField(
            model_name='contractcarveout',
            name='carveout_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent of billed amount; used when carveout_methodology=PCT_BILLED', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='contractcarveout',
            name='conditions',
            field=models.JSONField(blank=True, help_text='Optional. Null = always apply. Schema: {"operator": "AND"|"OR", "conditions": [{"field": "procedure_code"|"billed_amount"|"units"|"claim_type"|"modifiers_count", "op": "eq"|"neq"|"gt"|"gte"|"lt"|"lte"|"in"|"not_in", "value": <scalar or list>}]}. No nested groups.', null=True),
        ),
        migrations.AlterField(
            model_name='contractmethodology',
            name='conditions',
            field=models.JSONField(blank=True, help_text='Optional. Null = always apply. Schema: {"operator": "AND"|"OR", "conditions": [{"field": "<name>", "op": "eq"|"neq"|"gt"|"gte"|"lt"|"lte"|"in"|"not_in", "value": <scalar or list>}]}. Allowed fields: procedure_code, billed_amount, units, claim_type, modifiers_count. No nested groups.', null=True),
        ),
        migrations.AlterField(
            model_name='contractscope',
            name='specialty_code',
            field=models.ForeignKey(blank=True, db_column='specialty_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_scopes', to='core.refspecialty'),
        ),
        migrations.AlterField(
            model_name='contractversionaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
