# Generated by Django 5.2.11 on 2026-03-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_phase_b_contract_term'),
        ('core', '0025_alter_contractbaserate_options_and_more'),
    ]

    operations = [
    ]
