# Generated by Django 6.0.2 on 2026-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_phase_f_mppr'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contractbaserate',
            index=models.Index(fields=['version', 'rate_type'], name='cbr_version_rate_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contractversion',
            index=models.Index(fields=['contract', 'effective_start_date', 'effective_end_date', 'status'], name='cv_contract_dates_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='feeschedulerate',
            index=models.Index(fields=['fee_schedule', 'code_id', 'effective_start_date', 'effective_end_date'], name='fs_rates_fs_code_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['contract', 'status', 'effective_start_date', 'effective_end_date'], name='rule_ctr_stat_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['contract', 'version', 'status', 'effective_start_date', 'effective_end_date'], name='rule_ctr_ver_stat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['contract', 'version', 'specificity_score'], name='rule_ctr_ver_spec_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrulecondition',
            index=models.Index(fields=['pricing_rule', 'attribute_name', 'attribute_value'], name='cond_rule_attr_val_idx'),
        ),
    ]
