# Generated by Django 6.0.2 on 2026-04-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_step11a_operational_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierMultiplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, db_column='product_id', max_length=100, null=True)),
                ('network_id', models.CharField(blank=True, db_column='network_id', max_length=100, null=True)),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(
                    db_column='contract_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tier_multipliers',
                    to='core.providercontract',
                )),
                ('version', models.ForeignKey(
                    blank=True,
                    db_column='version_id',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tier_multipliers',
                    to='core.contractversion',
                )),
            ],
            options={
                'db_table': 'tier_multipliers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contractversion',
            name='product_id',
            field=models.CharField(blank=True, db_column='product_id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='tier_priority',
            field=models.IntegerField(db_column='tier_priority', default=0),
        ),
        migrations.AddIndex(
            model_name='contractversion',
            index=models.Index(fields=['product_id', 'tier_priority'], name='contract_version_prod_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='tiermultiplier',
            index=models.Index(
                fields=['contract', 'product_id', 'network_id', 'effective_start_date', 'effective_end_date'],
                name='tier_mult_ctr_prod_net_dt_idx',
            ),
        ),
    ]
