# Generated by Django 5.2.11 on 2026-06-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_extend_provider_org_stage1'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contractbaserate',
            name='cbr_version_rate_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractversion',
            name='cv_contract_dates_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeschedulerate',
            name='fs_rates_fs_code_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='rule_ctr_stat_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='rule_ctr_ver_stat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='rule_ctr_ver_spec_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrulecondition',
            name='cond_rule_attr_val_idx',
        ),
    ]
