# Generated by Django 6.0.2 on 2026-06-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_contract_product_scope_and_payer_network_type'),
        ('members', '0001_initial'),
        ('providers', '0002_add_network_new_fk_to_product_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimheader',
            name='billing_npi',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='claimheader',
            name='facility',
            field=models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_headers', to='providers.facility'),
        ),
        migrations.AddField(
            model_name='claimheader',
            name='member_fk',
            field=models.ForeignKey(blank=True, db_column='member_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_headers', to='members.member'),
        ),
        migrations.AddField(
            model_name='claimheader',
            name='rendering_provider',
            field=models.ForeignKey(blank=True, db_column='rendering_provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_headers', to='providers.provider'),
        ),
    ]
