# Generated by Django 6.0.2 on 2026-06-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_enrich_claim_header_stage3'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercontract',
            name='contract_origin_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('LEASED', 'Leased Network'), ('DELEGATED', 'Delegated')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='resolution_priority',
            field=models.SmallIntegerField(default=10, help_text='Lower value wins on tie. DIRECT=10, DELEGATED=15, LEASED=20.'),
        ),
        migrations.CreateModel(
            name='ClaimResolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('resolution_path', models.CharField(choices=[('CALLER_SUPPLIED', 'Caller Supplied'), ('LEGACY_PARTICIPATION', 'Legacy Participation'), ('CONTEXT_RESOLVER', 'Context Resolver')], max_length=30)),
                ('service_date', models.DateField()),
                ('resolver_inputs', models.JSONField(default=dict)),
                ('is_repricing', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('claim_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_logs', to='core.claimheader')),
                ('resolved_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_logs', to='core.providercontract')),
                ('resolved_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_logs', to='core.contractversion')),
            ],
            options={
                'db_table': 'claim_resolution_logs',
                'indexes': [models.Index(fields=['resolved_contract', 'service_date'], name='claim_resol_resolve_70180f_idx'), models.Index(fields=['claim_header'], name='claim_resol_claim_h_28ff99_idx')],
            },
        ),
    ]
