# Generated by Django 6.0.2 on 2026-07-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_phase_r1_backfill_resolution_priority'),
        ('products', '0002_add_legacy_provider_org_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercontract',
            name='payer_org',
            field=models.ForeignKey(blank=True, db_column='payer_org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='products.payerorganization'),
        ),
    ]
