# Generated by Django 6.0.2 on 2026-07-03 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_phase_c1_payer_org_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('AGREEMENT', 'Agreement'), ('RATE_EXHIBIT', 'Rate Exhibit'), ('AMENDMENT', 'Amendment'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(help_text='Path, URL, or external identifier for the source document.', max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.providercontract')),
            ],
            options={
                'db_table': 'contract_documents',
                'ordering': ['contract', '-uploaded_at'],
            },
        ),
    ]
