# Generated by Django 6.0.2 on 2026-07-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_phase_c2_contract_document'),
        ('providers', '0004_r6_migrate_contract_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('description', models.TextField()),
                ('what_changed', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='core.providercontract')),
            ],
            options={
                'db_table': 'contract_amendments',
                'ordering': ['contract', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractArrangement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('arrangement_type', models.CharField(choices=[('FEE_SCHEDULE', 'Fee Schedule'), ('DRG_CASE_RATE', 'DRG Case Rate'), ('PER_DIEM', 'Per Diem'), ('APC', 'APC'), ('ANESTHESIA', 'Anesthesia'), ('DRUG_ASP', 'Drug ASP'), ('CAPITATION', 'Capitation'), ('BUNDLED', 'Bundled'), ('VALUE_BASED', 'Value Based')], max_length=30)),
                ('claim_type', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='core.providercontract')),
            ],
            options={
                'db_table': 'contract_arrangements',
                'ordering': ['contract', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='arrangement',
            field=models.ForeignKey(blank=True, db_column='arrangement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='core.contractarrangement'),
        ),
        migrations.CreateModel(
            name='ContractCoveredEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ORG', 'Organization'), ('FACILITY', 'Facility'), ('PROVIDER', 'Provider')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='covered_entities', to='core.providercontract')),
                ('facility', models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_covered_entities', to='providers.facility')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_covered_entities', to='core.providerorganization')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_covered_entities', to='providers.provider')),
            ],
            options={
                'db_table': 'contract_covered_entities',
                'indexes': [models.Index(fields=['contract', 'entity_type'], name='cce_contract_entity_idx'), models.Index(fields=['organization'], name='cce_organization_idx'), models.Index(fields=['facility'], name='cce_facility_idx'), models.Index(fields=['provider'], name='cce_provider_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entity_type', 'ORG'), ('facility__isnull', True), ('organization__isnull', False), ('provider__isnull', True)), models.Q(('entity_type', 'FACILITY'), ('facility__isnull', False), ('organization__isnull', True), ('provider__isnull', True)), models.Q(('entity_type', 'PROVIDER'), ('facility__isnull', True), ('organization__isnull', True), ('provider__isnull', False)), _connector='OR'), name='cce_entity_type_matches_fk')],
            },
        ),
    ]
