# Generated by Django 6.0.2 on 2026-07-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_phase_c4_backfill_arrangements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractResolutionException',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('candidates', models.JSONField(default=list)),
                ('gathered_inputs', models.JSONField(default=dict)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contract_resolution_exceptions',
                'indexes': [models.Index(fields=['status', 'is_reviewed'], name='cre_status_reviewed_idx'), models.Index(fields=['trace_id'], name='cre_trace_id_idx')],
            },
        ),
    ]
