# Generated by Django 6.0.2 on 2026-07-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_phase_d3_resolution_exceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedFeeSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('basis_type', models.CharField(choices=[('MPFS', 'MPFS'), ('MSDRG', 'MSDRG'), ('APC', 'APC'), ('CUSTOM', 'Custom')], max_length=20)),
                ('year', models.IntegerField()),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'published_fee_schedules',
                'ordering': ['-year', 'name'],
                'managed': True,
                'indexes': [models.Index(fields=['basis_type', 'year'], name='pub_sched_type_year_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractRateBasis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percent of schedule amount, e.g. 120.00 = 120%', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_rule', models.OneToOneField(db_column='rule_id', on_delete=django.db.models.deletion.CASCADE, related_name='rate_basis', to='core.pricingrule')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.PROTECT, related_name='contract_bases', to='core.publishedfeeschedule')),
            ],
            options={
                'verbose_name_plural': 'contract rate bases',
                'db_table': 'contract_rate_bases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PublishedFeeScheduleRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.publishedfeeschedule')),
            ],
            options={
                'db_table': 'published_fee_schedule_rates',
                'managed': True,
                'indexes': [models.Index(fields=['schedule', 'code'], name='pub_sched_rate_sched_code_idx')],
            },
        ),
    ]
