# Generated by Django 6.0.2 on 2026-07-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_gap_a_rate_schedule_linkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEscalator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('annual_percentage', models.DecimalField(decimal_places=2, help_text='Annual compounding increase, e.g. 3.00 = 3%/yr', max_digits=6)),
                ('cap_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Optional max cumulative increase from base_year, e.g. 10.00 = 10% total cap', max_digits=6, null=True)),
                ('base_year', models.IntegerField(help_text='Anchor year for the base rate before escalation')),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='escalators', to='core.providercontract')),
                ('version', models.ForeignKey(blank=True, db_column='version_id', help_text='Null = applies to all rate-basis rules on the contract.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalators', to='core.contractversion')),
            ],
            options={
                'db_table': 'contract_escalators',
                'ordering': ['contract', '-effective_start_date'],
                'managed': True,
                'indexes': [models.Index(fields=['contract', 'effective_start_date'], name='contract_esc_cntr_start_idx')],
            },
        ),
    ]
