# Generated by Django 6.0.2 on 2026-07-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_gap_e_unified_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractscopeunified',
            options={'managed': True, 'ordering': ['contract', 'priority', 'id']},
        ),
        migrations.AlterField(
            model_name='contractscopeunified',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contractscopeunified',
            name='specialty_code',
            field=models.ForeignKey(blank=True, db_column='specialty_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_contract_scopes', to='core.refspecialty'),
        ),
    ]
