# Generated by Django 6.0.2 on 2026-06-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_extend_provider_org_stage1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('npi', models.CharField(db_index=True, max_length=15, unique=True)),
                ('ccn', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=50)),
                ('place_of_service_codes', models.JSONField(default=list)),
                ('address_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('npi', models.CharField(db_index=True, max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('credential', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_taxonomy', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.refspecialty')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderAffiliation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor'), ('LOCUM', 'Locum Tenens'), ('ADMITTING', 'Admitting'), ('COVERING', 'Covering')], default='EMPLOYEE', max_length=30)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_affiliations', to='core.providerorganization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_affiliations',
            },
        ),
        migrations.CreateModel(
            name='ProviderNetworkParticipation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_NETWORK', 'In-Network'), ('OUT_OF_NETWORK', 'Out-of-Network'), ('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2')], default='IN_NETWORK', max_length=20)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('specialty_scope', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_participations', to='core.payernetwork')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_participations', to='core.providerorganization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_participations', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_network_participations',
            },
        ),
        migrations.CreateModel(
            name='FacilityNetworkParticipation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='IN_NETWORK', max_length=20)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_participations', to='providers.facility')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payernetwork')),
            ],
            options={
                'db_table': 'facility_network_participations',
                'indexes': [models.Index(fields=['facility', 'network', 'effective_date'], name='facility_ne_facilit_465b8a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['npi'], name='providers_npi_df1406_idx'),
        ),
        migrations.AddIndex(
            model_name='provideraffiliation',
            index=models.Index(fields=['provider', 'organization', 'effective_date'], name='provider_af_provide_c9bf93_idx'),
        ),
        migrations.AddIndex(
            model_name='providernetworkparticipation',
            index=models.Index(fields=['organization', 'network', 'effective_date'], name='provider_ne_organiz_9635a7_idx'),
        ),
        migrations.AddIndex(
            model_name='providernetworkparticipation',
            index=models.Index(fields=['provider', 'network', 'effective_date'], name='provider_ne_provide_b4aae3_idx'),
        ),
        migrations.AddConstraint(
            model_name='providernetworkparticipation',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('provider__isnull', False), _connector='OR'), name='participation_must_have_org_or_provider'),
        ),
    ]
