# Generated by Django 6.0.2 on 2026-06-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providernetworkparticipation',
            name='network_new',
            field=models.ForeignKey(blank=True, db_column='network_new_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_participations_new', to='products.network'),
        ),
    ]
