# Generated by Django 6.0.2 on 2026-06-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_phase_r1_schema_foundation'),
        ('providers', '0002_add_network_new_fk_to_product_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='providernetworkparticipation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_participations', to='core.providercontract'),
        ),
        migrations.AddField(
            model_name='providernetworkparticipation',
            name='participation_source',
            field=models.CharField(choices=[('DIRECT_CONTRACT', 'Direct Contract'), ('NETWORK_ARRANGEMENT', 'Network Arrangement')], default='NETWORK_ARRANGEMENT', max_length=30),
        ),
    ]
