from django.urls import path
from core.api.views import (
    ContractListView,
    ContractDetailView,
    ContractMethodologyListCreateView,
    ContractRuleListView,
    ContractSnapshotView,
    ContractOutlierRuleListCreateView,
    ContractStopLossRuleListCreateView,
    RuleListView,
    RuleDetailView,
    RuleHistoryView,
    RuleConflictsView,
    RuleCheckConflictsView,
    FeeScheduleListView,
    CptHcpcsCodeListView,
    MpfsRvuListView,
    DrgListView,
    ApcListView,
    Icd10CmListView,
    Icd10PcsListView,
    AspPricingListView,
    RevenueCodeListView,
    SpecialtyListView,
    ProcedureCodeListView,
    ModifierListView,
    PriceLineView,
    PriceClaimView,
    PriceClaimSimulateView,
    SimulateLineView,
    ClaimListCreateView,
    ClaimDetailView,
    ClaimPriceView,
    BulkPriceClaimsView,
    ValidateContractView,
    ValidateContractsBulkView,
    ContractConflictsView,
    ContractConflictResolveView,
    ContractExplorerView,
    ContractVersionDetailView,
    ContractVersionAuditView,
    ContractVersionActivateView,
    ContractVersionArchiveView,
    ResolveContextView,
    RepriceClaimView,
    RepriceClaimBatchView,
    ProviderListView,
    ProviderNetworkStatusView,
    MemberEnrollmentView,
    ProductListView,
)

urlpatterns = [
    path('contracts/', ContractListView.as_view(), name='api-contract-list'),
    path('contracts/<int:pk>/', ContractDetailView.as_view(), name='api-contract-detail'),
    path('contracts/<int:pk>/explorer/', ContractExplorerView.as_view(), name='api-contract-explorer'),
    path('contracts/<int:pk>/methodologies/', ContractMethodologyListCreateView.as_view(), name='api-contract-methodologies'),
    path('contracts/<int:pk>/rules/', ContractRuleListView.as_view(), name='api-contract-rules'),
    path('contracts/<int:pk>/snapshot/', ContractSnapshotView.as_view(), name='api-contract-snapshot'),
    path('contracts/<int:pk>/outlier-rules/', ContractOutlierRuleListCreateView.as_view(), name='api-contract-outlier-rules'),
    path('contracts/<int:pk>/stop-loss-rules/', ContractStopLossRuleListCreateView.as_view(), name='api-contract-stop-loss-rules'),
    path('fee-schedules/', FeeScheduleListView.as_view(), name='api-fee-schedules'),
    path('cpt-hcpcs-codes/', CptHcpcsCodeListView.as_view(), name='api-cpt-hcpcs-codes'),
    path('mpfs-rvu/', MpfsRvuListView.as_view(), name='api-mpfs-rvu'),
    path('drg/', DrgListView.as_view(), name='api-drg'),
    path('apc/', ApcListView.as_view(), name='api-apc'),
    path('icd10-cm/', Icd10CmListView.as_view(), name='api-icd10-cm'),
    path('icd10-pcs/', Icd10PcsListView.as_view(), name='api-icd10-pcs'),
    path('asp-pricing/', AspPricingListView.as_view(), name='api-asp-pricing'),
    path('revenue-codes/', RevenueCodeListView.as_view(), name='api-revenue-codes'),
    path('specialties/', SpecialtyListView.as_view(), name='api-specialties'),
    path('procedure-codes/', ProcedureCodeListView.as_view(), name='api-procedure-codes'),
    path('modifiers/', ModifierListView.as_view(), name='api-modifiers'),
    path('rules/', RuleListView.as_view(), name='api-rule-list'),
    path('rules/check-conflicts/', RuleCheckConflictsView.as_view(), name='api-rule-check-conflicts'),
    path('rules/<int:pk>/', RuleDetailView.as_view(), name='api-rule-detail'),
    path('rules/<int:pk>/conflicts/', RuleConflictsView.as_view(), name='api-rule-conflicts'),
    path('rules/<int:rule_id>/history/', RuleHistoryView.as_view(), name='api-rule-history'),
    path('price-line/', PriceLineView.as_view(), name='api-price-line'),
    path('simulate-line/', SimulateLineView.as_view(), name='api-simulate-line'),
    path('price-claim/', PriceClaimView.as_view(), name='price-claim'),
    path('price-claim-simulate/', PriceClaimSimulateView.as_view(), name='price-claim-simulate'),
    path('price-claims-bulk/', BulkPriceClaimsView.as_view(), name='price-claims-bulk'),
    path('claims/', ClaimListCreateView.as_view(), name='api-claim-list-create'),
    path('claims/<int:pk>/', ClaimDetailView.as_view(), name='api-claim-detail'),
    path('claims/<int:pk>/price/', ClaimPriceView.as_view(), name='api-claim-price'),
    # Step 10: Contract conflict validation
    path('validate-contract/<int:pk>/', ValidateContractView.as_view(), name='api-validate-contract'),
    # Step 12d: Bulk contract validation
    path('validate-contracts/bulk/', ValidateContractsBulkView.as_view(), name='api-validate-contracts-bulk'),
    # Step 12a: Conflict warnings panel
    path('contracts/<int:pk>/conflicts/', ContractConflictsView.as_view(), name='api-contract-conflicts'),
    path('contracts/<int:pk>/conflicts/<int:result_id>/resolve/', ContractConflictResolveView.as_view(), name='api-contract-conflict-resolve'),
    # Step 12b: Version lifecycle
    path('contract-versions/<int:pk>/', ContractVersionDetailView.as_view(), name='api-contract-version-detail'),
    path('contract-versions/<int:pk>/activate/', ContractVersionActivateView.as_view(), name='api-contract-version-activate'),
    path('contract-versions/<int:pk>/archive/', ContractVersionArchiveView.as_view(), name='api-contract-version-archive'),
    path('contracts/<int:pk>/version-audit/', ContractVersionAuditView.as_view(), name='api-contract-version-audit'),
    path('resolve-context/', ResolveContextView.as_view(), name='api-resolve-context'),
    path('reprice-claim/', RepriceClaimView.as_view(), name='api-reprice-claim'),
    path('reprice-claim-batch/', RepriceClaimBatchView.as_view(), name='api-reprice-claim-batch'),
    path('providers/', ProviderListView.as_view(), name='api-provider-list'),
    path(
        'providers/<int:provider_id>/network-status/',
        ProviderNetworkStatusView.as_view(),
        name='api-provider-network-status',
    ),
    path(
        'members/<str:member_id>/enrollment/',
        MemberEnrollmentView.as_view(),
        name='api-member-enrollment',
    ),
    path('products/', ProductListView.as_view(), name='api-product-list'),
]
