"""
Use-case registry for DEMO-UC-* transactional seed data.

Single source of truth for ~36 identity-first pricing scenarios.
expected_allowed is intentionally None — fill by hand after manual pricing verification.
"""
from __future__ import annotations

from datetime import date

SERVICE_DATE = "2025-06-15"
PREFIX = "DEMO-UC-"

# Shared cast natural keys (all prefixed DEMO-UC- per safety rules)
CAST = {
    "payer_id": "DEMO-UC-PAYER-01",
    "org_in": "DEMO-UC-ORG-IN",
    "org_oon": "DEMO-UC-ORG-OON",
    "org_payer_core": "DEMO-UC-ORG-PAYER",
    "billing_npi_in": "DEMO-UC-NPI01",
    "billing_npi_oon": "DEMO-UC-NPI02",
    "render_pcp": "DEMO-UC-NPI03",
    "render_surg": "DEMO-UC-NPI04",
    "render_anes": "DEMO-UC-NPI05",
    "net_ppo": "DEMO-UC-NET-PPO",
    "net_hmo": "DEMO-UC-NET-HMO",
    "net_tier": "DEMO-UC-NET-TIER",
    "prod_commercial": "DEMO-UC-PROD-COMM",
    "prod_ma": "DEMO-UC-PROD-MA",
    "prod_medicaid": "DEMO-UC-PROD-MCAID",
}


def _line(
    procedure_code: str,
    billed_amount: str = "200.00",
    units: int | float = 1,
    modifiers: list | None = None,
    revenue_code: str = "",
) -> dict:
    return {
        "procedure_code": procedure_code,
        "billed_amount": billed_amount,
        "units": units,
        "modifiers": modifiers or [],
        "revenue_code": revenue_code,
    }


USE_CASES: list[dict] = [
    # ── RESOLUTION A1–A10 ───────────────────────────────────────────────────
    {
        "id": "A1",
        "family": "RESOLUTION",
        "description": "In-network member + billing org resolves to FLAT contract",
        "member_id": "DEMO-UC-MEM-A1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-A1 FLAT_RATE 99213 @ $100; IN_NETWORK on PPO",
    },
    {
        "id": "A2",
        "family": "RESOLUTION",
        "description": "Out-of-network billing org — contract resolution fails (OON)",
        "member_id": "DEMO-UC-MEM-A1",
        "billing_npi": CAST["billing_npi_oon"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "OON",
        "expected_allowed": None,
        "notes": "OON org participation; member enrolled but provider OON",
    },
    {
        "id": "A3",
        "family": "RESOLUTION",
        "description": "Member not enrolled — no coverage",
        "member_id": "DEMO-UC-MEM-NOENROLL",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "NO_CONTRACT",
        "expected_allowed": None,
        "notes": "No Enrollment row; resolver cannot scope LOB/product",
    },
    {
        "id": "A4",
        "family": "RESOLUTION",
        "description": "Terminated enrollment before service date",
        "member_id": "DEMO-UC-MEM-TERMED",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "NO_CONTRACT",
        "expected_allowed": None,
        "notes": "Enrollment ended 2025-05-01",
    },
    {
        "id": "A5",
        "family": "RESOLUTION",
        "description": "LOB-specific contract wins over generic",
        "member_id": "DEMO-UC-MEM-MA",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-A5 MA LOB contract via ContractScope; member on MA product",
    },
    {
        "id": "A6",
        "family": "RESOLUTION",
        "description": "Product-scoped contract beats LOB-only scope",
        "member_id": "DEMO-UC-MEM-A1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99214", "250.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-A6 product ContractProductScope vs DEMO-UC-A6B LOB-only",
    },
    {
        "id": "A7",
        "family": "RESOLUTION",
        "description": "Org has no contract on member's network",
        "member_id": "DEMO-UC-MEM-HMO",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "OON",
        "expected_allowed": None,
        "notes": "Member on HMO network; contract only on PPO network",
    },
    {
        "id": "A8",
        "family": "RESOLUTION",
        "description": "Tiered network participation (TIER_2)",
        "member_id": "DEMO-UC-MEM-TIER",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "ProviderNetworkParticipation TIER_2 on tiered network",
    },
    {
        "id": "A9",
        "family": "RESOLUTION",
        "description": "Rendering provider not affiliated with billing org",
        "member_id": "DEMO-UC-MEM-A1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_surg"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "Pricing still succeeds; affiliation_verified=False in context",
    },
    {
        "id": "A10",
        "family": "RESOLUTION",
        "description": "Direct contract_id override bypasses resolution",
        "member_id": "DEMO-UC-MEM-A1",
        "billing_npi": CAST["billing_npi_oon"],
        "rendering_npi": None,
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "API override_contract_id=DEMO-UC-A1; not auto-resolved from OON NPI",
    },
    # ── METHODOLOGY B1–B8 ───────────────────────────────────────────────────
    {
        "id": "B1",
        "family": "METHODOLOGY",
        "description": "FLAT_RATE professional 99213",
        "member_id": "DEMO-UC-MEM-B1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B1 flat_rate=$100.00",
    },
    {
        "id": "B2",
        "family": "METHODOLOGY",
        "description": "PCT_BILLED (PERCENT) on 99214",
        "member_id": "DEMO-UC-MEM-B2",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99214", "250.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B2 multiplier=0.80 → $200.00",
    },
    {
        "id": "B3",
        "family": "METHODOLOGY",
        "description": "RBRVS on 29881",
        "member_id": "DEMO-UC-MEM-B3",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_surg"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("29881", "5000.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B3 fee schedule $500 × 1.5 = $750",
    },
    {
        "id": "B4",
        "family": "METHODOLOGY",
        "description": "PER_DIEM institutional with revenue code",
        "member_id": "DEMO-UC-MEM-B4",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": None,
        "service_date": SERVICE_DATE,
        "claim_type": "institutional",
        "lines": [_line("0120", "8000.00", units=3, revenue_code="0120")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B4 flat_rate=$400/day × 3 units",
    },
    {
        "id": "B5",
        "family": "METHODOLOGY",
        "description": "Claim-level DRG DRG-470",
        "member_id": "DEMO-UC-MEM-B5",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": None,
        "service_date": SERVICE_DATE,
        "claim_type": "institutional",
        "lines": [_line("470", "50000.00", units=1)],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B5 DRG base $6000 × weight 2.0; drg_code=470 on claim",
    },
    {
        "id": "B6",
        "family": "METHODOLOGY",
        "description": "APC institutional outpatient",
        "member_id": "DEMO-UC-MEM-B6",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": None,
        "service_date": SERVICE_DATE,
        "claim_type": "institutional",
        "lines": [_line("5121", "3000.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B6 APC weight 1.5 × CF $100",
    },
    {
        "id": "B7",
        "family": "METHODOLOGY",
        "description": "ANESTHESIA 00100 with 99100 add-on line",
        "member_id": "DEMO-UC-MEM-B7",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_anes"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [
            _line("00100", "500.00"),
            _line("99100", "100.00"),
        ],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B7 anesthesia base units 5 × CF 45; +99100 flat add-on rule",
    },
    {
        "id": "B8",
        "family": "METHODOLOGY",
        "description": "ASP drug pricing J1885",
        "member_id": "DEMO-UC-MEM-B8",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("J1885", "500.00", units=2)],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-B8 ASP J1885 payment_limit × units",
    },
    # ── MODIFIER / POLICY C1–C10 ────────────────────────────────────────────
    {
        "id": "C1",
        "family": "MODIFIER",
        "description": "Modifier -50 bilateral on 29881",
        "member_id": "DEMO-UC-MEM-C1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_surg"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("29881", "5000.00", modifiers=["50"])],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "RefModifier 50 @ 150%; RBRVS base then bilateral adj",
    },
    {
        "id": "C2",
        "family": "MODIFIER",
        "description": "Multi-line mixed methodology claim",
        "member_id": "DEMO-UC-MEM-C2",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00"), _line("73030", "150.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C2 FLAT 99213 + FLAT 73030 on same contract",
    },
    {
        "id": "C3",
        "family": "MODIFIER",
        "description": "MPPR on multiple imaging lines 70450",
        "member_id": "DEMO-UC-MEM-C3",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [
            _line("70450", "800.00"),
            _line("70450", "800.00"),
        ],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C3 MPPR 100%/50% on 70450 RBRVS lines",
    },
    {
        "id": "C4",
        "family": "MODIFIER",
        "description": "Carve-out excludes 99100",
        "member_id": "DEMO-UC-MEM-C4",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_anes"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99100", "200.00"), _line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C4 carveout EXCLUDE on 99100",
    },
    {
        "id": "C5",
        "family": "MODIFIER",
        "description": "Line-level PCT_BILLED_CAP (cap/floor)",
        "member_id": "DEMO-UC-MEM-C5",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "500.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C5 LINE PCT_BILLED_CAP 60%",
    },
    {
        "id": "C6",
        "family": "MODIFIER",
        "description": "Claim outlier above threshold",
        "member_id": "DEMO-UC-MEM-C6",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "5000.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C6 outlier PER_CLAIM threshold $1000 @ 80%",
    },
    {
        "id": "C7",
        "family": "MODIFIER",
        "description": "Stop-loss on SL-TRIG with cost_amount",
        "member_id": "DEMO-UC-MEM-C7",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("SL-TRIG", "15000.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C7 stop-loss threshold $1000 @ 50% with cost on line",
    },
    {
        "id": "C8",
        "family": "MODIFIER",
        "description": "Blending ADD on claim total",
        "member_id": "DEMO-UC-MEM-C8",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C8 blending ADD 10% of billed (pattern from DEMO_POLICY)",
    },
    {
        "id": "C9",
        "family": "MODIFIER",
        "description": "Code-group condition matches 36415",
        "member_id": "DEMO-UC-MEM-C9",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("36415", "50.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C9 CodeGroup LAB_CODES contains 36415",
    },
    {
        "id": "C10",
        "family": "MODIFIER",
        "description": "Specific 99214 rule beats wildcard professional rule",
        "member_id": "DEMO-UC-MEM-C10",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99214", "300.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-C10 specific flat $175 vs wildcard $100",
    },
    # ── EDGE D1–D4 ────────────────────────────────────────────────────────────
    {
        "id": "D1",
        "family": "EDGE",
        "description": "Unknown procedure code — denied no rule",
        "member_id": "DEMO-UC-MEM-D1",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("XXXXX", "100.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "Engine returns DENIED_NO_RULE; claim status may be non-SUCCESS",
    },
    {
        "id": "D2",
        "family": "EDGE",
        "description": "Service date outside contract effective window",
        "member_id": "DEMO-UC-MEM-D2",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": "2024-01-01",
        "claim_type": "professional",
        "lines": [_line("99213", "200.00")],
        "expected_status": "NO_CONTRACT",
        "expected_allowed": None,
        "notes": "Contract effective 2025-01-01 – 2025-12-31 only",
    },
    {
        "id": "D3",
        "family": "EDGE",
        "description": "Zero billed on PCT_BILLED line",
        "member_id": "DEMO-UC-MEM-D3",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99214", "0.00")],
        "expected_status": "SUCCESS",
        "expected_allowed": None,
        "notes": "DEMO-UC-D3 PCT 80% of $0 = $0",
    },
    {
        "id": "D4",
        "family": "EDGE",
        "description": "Unknown modifier ignored",
        "member_id": "DEMO-UC-MEM-D4",
        "billing_npi": CAST["billing_npi_in"],
        "rendering_npi": CAST["render_pcp"],
        "service_date": SERVICE_DATE,
        "claim_type": "professional",
        "lines": [_line("99213", "200.00", modifiers=["ZZ"])],
        "expected_status": "SUCCESS",
        "expected_allowed": "100.00",
        "notes": "Modifier ZZ not in RefModifier — skipped, no adjustment (flat $100). "
                 "NOTE: do not use 'XX' here — XX is a seeded 0% fixture that zeroes the line.",
    },
]

USE_CASE_IDS = [uc["id"] for uc in USE_CASES]
