# Generated by Django 6.0.2 on 2026-06-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('subscriber_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('relationship_to_subscriber', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('DEPENDENT', 'Dependent'), ('OTHER', 'Other')], default='SELF', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members',
                'indexes': [models.Index(fields=['member_id'], name='members_member__12a4b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField(db_index=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='products.product')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.member')),
            ],
            options={
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['member', 'effective_date'], name='enrollments_member__7e55d4_idx'), models.Index(fields=['member', 'termination_date'], name='enrollments_member__e1c742_idx')],
            },
        ),
    ]
