# Generated by Django 6.0.2 on 2026-06-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_extend_provider_org_stage1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('MEDICARE_ADVANTAGE', 'Medicare Advantage'), ('MEDICAID', 'Medicaid'), ('EXCHANGE', 'Exchange / ACA'), ('SELF_FUNDED', 'Self-Funded'), ('MEDICARE_FFS', 'Medicare Fee-for-Service')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Lines of Business',
                'db_table': 'lines_of_business',
            },
        ),
        migrations.CreateModel(
            name='PayerOrganization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('payer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payer_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('MEDICARE_ADVANTAGE', 'Medicare Advantage'), ('MEDICAID', 'Medicaid'), ('SELF_FUNDED', 'Self-Funded'), ('TPA', 'TPA'), ('CMS', 'CMS/Medicare FFS')], max_length=30)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payer_organizations',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('network_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('network_type', models.CharField(choices=[('PPO', 'PPO'), ('HMO', 'HMO'), ('EPO', 'EPO'), ('POS', 'POS'), ('ACO', 'ACO'), ('NARROW', 'Narrow'), ('TIERED', 'Tiered')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_payer_network', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_record', to='core.payernetwork')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='products.payerorganization')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.lineofbusiness')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.payerorganization')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductNetworkConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('ALL', 'All'), ('PROFESSIONAL', 'Professional'), ('INSTITUTIONAL', 'Institutional'), ('BEHAVIORAL_HEALTH', 'Behavioral Health')], default='ALL', max_length=30)),
                ('effective_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='products.network')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_configs', to='products.product')),
            ],
            options={
                'db_table': 'product_network_configs',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['payer', 'effective_date'], name='products_payer_i_ffdb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='productnetworkconfig',
            index=models.Index(fields=['product', 'claim_type', 'effective_date'], name='product_net_product_61fb18_idx'),
        ),
    ]
