# Generated by Django 6.0.2 on 2026-06-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_enrich_claim_header_stage3'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerorganization',
            name='legacy_provider_org',
            field=models.OneToOneField(blank=True, db_column='legacy_provider_org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_org_record', to='core.providerorganization'),
        ),
    ]
